### PR TITLE
build: downgrade CUDA toolkit (PROOF-916)

### PR DESCRIPTION
**Pull request by jacobtrombetta**
# Rationale for this change
The NVIDIA drivers required to run the CUDA toolkit 12.6 cannot be installed on Kubernetes clusters successfully. The version that can be installed is 550, which corresponds to [CUDA toolkit 12.4](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html). This PR downgrades the CUDA toolkit.

Downgrading the CUDA toolkit with the version of clang we are using causes the following error:
```
In file included from external/local_cuda/cuda/include/cub/cub.cuh:62:
In file included from external/local_cuda/cuda/include/cub/device/device_adjacent_difference.cuh:42:
In file included from external/local_cuda/cuda/include/cub/device/dispatch/dispatch_adjacent_difference.cuh:40:
In file included from external/local_cuda/cuda/include/cub/agent/agent_adjacent_difference.cuh:46:
In file included from external/local_cuda/cuda/include/thrust/system/cuda/detail/core/util.h:42:
external/local_cuda/cuda/include/thrust/type_traits/is_contiguous_iterator.h:150:3: error: use of undeclared identifier '_VSTD'
  150 |   _VSTD::__wrap_iter<Iterator>
      |   ^
external/local_cuda/cuda/include/thrust/type_traits/is_contiguous_iterator.h:150:22: error: 'Iterator' does not refer to a value
  150 |   _VSTD::__wrap_iter<Iterator>
      |                      ^
external/local_cuda/cuda/include/thrust/type_traits/is_contiguous_iterator.h:148:20: note: declared here
  148 | template <typename Iterator>
      |                    ^
external/local_cuda/cuda/include/thrust/type_traits/is_contiguous_iterator.h:151:1: error: expected unqualified-id
  151 | > : true_type {};
      | ^
3 errors generated when compiling for sm_70.
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 54.200s, Critical Path: 10.23s
INFO: 2588 processes: 2032 internal, 556 local.
ERROR: Build did NOT complete successfully
```
This PR includes a temporary workaround for this error.

# What changes are included in this PR?
- Downgrade the CUDA toolkit to 12.4.1 to work with Kubernetes pods.
- Create a temporary workaround for `_VSTD` build error.

# Are these changes tested?
Yes

### CODE REVIEW

**Comment by rnburn** [comment]
Instead of defining _VSTD, can you try including `#include <ciso646>` -- that's where _LIBCPP_VERSION is defined, https://stackoverflow.com/q/31657499


If that works, I think it would be a better way to work around the issue.

**Comment by jacobtrombetta** [comment]
> Instead of defining _VSTD, can you try including `#include <ciso646>` -- that's where _LIBCPP_VERSION is defined, https://stackoverflow.com/q/31657499
> 
> If that works, I think it would be a better way to work around the issue.

I replaced the `#define` with `#include <ciso646>` and also tried `#include <version>`, both mentioned in the stackoverflow link, but I got the original error. 

I was able to remove the `_LIBCPP_BEGIN_NAMESPACE_STD _LIBCPP_END_NAMESPACE_STD` line.

**Comment by rnburn** [comment]
Can you add a header file sxt/base/device/cub that includes cub/cub.cuh and has the workaround? Then the code will be more isolated and easier to maintain.

**Comment by jacobtrombetta** [comment]
> sxt/base/device/cub

Great idea, added.

**Review by rnburn — APPROVED** [review]

**Pull request merged**
