### PR TITLE
build: clean up nix environement (PROOF-537)

### PR DESCRIPTION
**Pull request by rnburn**
# Rationale for this change

Drop clang wrapper to simplify nix environment.

# What changes are included in this PR?

* Tweaked build options for llvm so that we don't need a clang wrapper
* Removed clang wrapper script

# Are these changes tested?

Yes

### CODE REVIEW

**Comment by tlovell-sxt** [comment]
gonna try this out locally

**Comment by rnburn** [comment]
> gonna try this out locally

Just a heads up. The part that builds clang is going to be slow. You might want to run overnight.

**Comment by tlovell-sxt** [comment]
Yeah, I got building on main to work after letting it build in this branch overnight, but now that I've moved back to this branch it's rebuilding clang again

**Review by tlovell-sxt — APPROVED** [review]
LGTM and build is passing in my nix env

**Pull request merged**
